### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by shaunhutch** [UBC-MDS/drug_consumption_prediction#19]
Okay I have made some updates on the file. However, I am still getting this error below on the model:

`$ python src/drug_consumption_prediction_model.py --data_path=data/processed --result_path=results
/opt/miniconda3/envs/522/lib/python3.10/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(
/opt/miniconda3/envs/522/lib/python3.10/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/opt/miniconda3/envs/522/lib/python3.10/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(
/opt/miniconda3/envs/522/lib/python3.10/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/opt/miniconda3/envs/522/lib/python3.10/site-packages/dataframe_image/_pandas_accessor.py:69: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  html = '<div>' + obj.render() + '</div>'
objc[22629]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb536ddec8) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/107.0.5304.121/Libraries/libGLESv2.dylib (0x1173dded8). One of the two will be used. Which one is undefined.
[1130/173723.574178:INFO:headless_shell.cc(657)] Written to file /var/folders/13/ygm89p7150n7xplw3qr6zqt80000gr/T/tmpu961zcvw/temp.png.`

I thought we had fixed the issue with stratified?

Also, when I run the Makefile, specifically the `preprocess.py`, the first line of the processed/train.csv is 
,,,,6.0,7.0,8.0,9.0,10.0,,,13,17,18,19,20,28,29,31
Which is causing errors in the model script.

I can't figure out why this is happening

**Comment by brabbit61** [comment]
While reading the file, we have to pass a list of column headers (present in the data mapping JSON file). I have used the following function call to read the file, you can replace it with `read_csv()`:
> `df = pd.read_table(in_path, index_col=0, names=mappings["column_headers"], delimiter=',')`

**Comment by ritisha2000** [comment]
These are the errors I mentioned before about there not being enough instances for each class, so it complains when you make the folds for cross-validation. I'm going to reduce the number of folds to avoid this error. The other one is a future warning.

**Comment by ritisha2000** [comment]
I did replace the function with `read_csv`. I thought the error was corrected.

**Comment by shaunhutch** [comment]
Issue resolved
